Repository tiangolo/meinheld-gunicorn-flask-docker, pull requests merged in 2024-03, with the labels that each got.

#128 🔥 Remove Alpine support
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  README.md
  docker-images/python3.7-alpine3.8.dockerfile
  docker-images/python3.8-alpine3.11.dockerfile
  docker-images/python3.9-alpine3.13.dockerfile
  pyproject.toml
  scripts/process_all.py
Labels: refactor

#125 👷 Update latest-changes GitHub Action
  .github/workflows/latest-changes.yml
Labels: internal

#137 📝 Update test badge in `README.md`
  README.md
Labels: docs

#138 ✨ Add support for multiarch builds, including ARM (e.g. Mac M1)
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  scripts/build-push-all.sh
  scripts/build-push.sh
  scripts/build.sh
  scripts/docker-login.sh
  scripts/test-all.sh
  scripts/test.sh
Labels: feature

#139 🐛 Fix latest-changes GitHub Action
  .github/workflows/latest-changes.yml
Labels: internal

#140 🐛 Fix latest-changes GitHub Action, take 2
  .github/workflows/latest-changes.yml
Labels: bug

#141 🔧 Update `latest-changes.yml`
  .github/workflows/latest-changes.yml
Labels: internal

#146 🔧 Add GitHub templates for discussions and issues, and security policy
  .github/DISCUSSION_TEMPLATE/questions.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/privileged.yml
  SECURITY.md
Labels: internal
